aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/mock/yarn.lock" }}-{{ checksum "packages/schema/yarn.lock" }}-{{ checksum "packages/playground/yarn.lock" }}
      # fallback to using the latest cache if no exact match is found
      - dependencies-

  - &save-cache
    paths:
      - node_modules
      - packages/mock/node_modules
      - packages/schema/node_modules
      - packages/playground/node_modules
    key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/mock/yarn.lock" }}-{{ checksum "packages/schema/yarn.lock" }}-{{ checksum "packages/playground/yarn.lock" }}

version: 2
jobs:
  test:
    docker:
      - image: node:9.3.0

    steps:
      - checkout
      - restore_cache: *restore-cache

      - run:
          name: Install Deps
          command: yarn install

      - run:
          name: Link Lerna
          command: yarn lerna bootstrap

      - save_cache: *save-cache

      - run:
          name: Check Style
          command: yarn check-style

      - run:
          name: Build
          command: yarn lerna run build

      - run:
          name: Lint
          command: yarn lerna run lint

      - run:
          name: Test
          command: yarn lerna run test

  integration:
    docker:
      - image: node:9.3.0

    steps:
      - checkout
      - restore_cache: *restore-cache

      - run:
          name: Install Deps
          command: yarn install

      - run:
          name: Link Lerna
          command: yarn lerna bootstrap

      - save_cache: *save-cache

      - run:
          name: Build
          command: yarn lerna run build

      - run:
          name: Mock Server
          background: true
          working_directory: ./packages/mock
          command: yarn mock-server

      - run:
          name: Integration Tests
          working_directory: ./packages/schema
          command: node tests/cli.js http://localhost:4000/graphql

  deploy:
    docker:
      - image: node:9.3.0

    steps:
      - checkout
      - restore_cache: *restore-cache

      - run:
          name: Install Deps
          command: yarn install

      - run:
          name: Link Lerna
          command: yarn lerna bootstrap

      - save_cache: *save-cache

      - run:
          name: Build
          command: yarn lerna run build

      - run:
          name: Build and Deploy Playground
          working_directory: ./packages/playground
          command: yarn deploy

workflows:
  version: 2
  test:
    jobs:
      - test
      - integration
      - deploy:
          requires:
            - test
            - integration
          filters:
            branches:
              only: master