aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - dependencies-

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}

version: 2
jobs:
  test:
    docker:
      - image: node:9.3.0

    steps:
      - checkout
      - restore_cache: *restore-cache

      - run:
          name: Install Deps
          command: yarn install

      - save_cache: *save-cache

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Check Style
          command: yarn check-style

  deploy:
    docker:
      - image: node:9.3.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Generate Schema JSON
          command: yarn generate-schema

      - run:
          name: Setup the Environment for Publishing
          command: printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc

      - run:
          name: Publish Package to NPM
          command: npm publish --access=public

workflows:
  version: 2
  test:
    jobs:
      - test
      - hold:
          type: approval
          requires:
           - test
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - hold
