aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - dependencies-

  - &save-cache
    paths:
      - node_modules
      - packages/mock/node_modules
      - packages/schema/node_modules
    key: dependencies-{{ checksum "package.json" }}

version: 2
jobs:
  test:
    docker:
      - image: node:9.3.0

    steps:
      - checkout
      - restore_cache: *restore-cache

      - run:
          name: Install Deps
          command: yarn install

      - run:
          name: Link Lerna
          command: yarn lerna bootstrap

      - save_cache: *save-cache

      - run:
          name: Check Style
          command: yarn check-style

      - run:
          name: Build
          command: yarn lerna run build

      - run:
          name: Lint
          command: yarn lerna run lint

      - run:
          name: Test
          command: yarn lerna run test

# TODO: Add Mock Resolver Test

workflows:
  version: 2
  test:
    jobs:
      - test
